### ISSUE TITLE
Missing? instruction to allow cifs though windows firewall

### ISSUE THREAD

**Issue by jan-glx** [jjkeijser/cifs-over-ssh#1]
While the instruction describe how to allow the ssh connection through windows firewall, it does not mention that the cifs connection through the virtual interface must be allowed as well –  at least I did not see it.

Allowing the cifs connection is possible by
   enabling file & printer sharing in windows settings / setting the current connection to private
or – and probably best – by 
    **disabling the firewall for for the virtual adapters** as described here:
https://superuser.com/questions/1583758/disable-the-windows-10-firewall-for-just-one-network-adapter
EDIT: this results in a warning by windows firewall, a better solution might be to make the virtual adapter connections private
e.g. using: https://superuser.com/a/1160447

**Comment by jjkeijser** [comment]
I am wondering what is different about your setup compared to others, as nobody has mentioned this to me before (which surprises me, actually).
I just ran the tutorial on a brand-new Windows 11 22H2 laptop with the firewall enabled and it "just worked" for me. I cannot pinpoint exactly why this worked (the loopback adapter is in the Public zone) but it does like it always has in the past for me.

**Comment by jan-glx** [comment]
Hm. Maybe you have "Network discovery turned on" for public networks and I had not? I checked twice (turning it on and off again) before posting here.... but then let's close this and see if some else runs into the same issue.
