### ISSUE TITLE
Accessing windows print server

### ISSUE THREAD

**Issue by watercrossing** [jjkeijser/cifs-over-ssh#3]
Thank you for the tutorials, they worked first try!

I can see the shared printers on `\\10.255.255.2` (shared by Windows Server), but when I try to connect to them I get (instantaneously) the error message: "Operation could not be completed (error 0x00000709) Double check the printer name and make sure that the printer is connected to the network."
Do you know what I need to change to be able to connect to the printers? How do I debug the connection requests?

**Comment by watercrossing** [comment]
I think I have identified the issue: Windows 11 22H2 changed the default behaviour for printer connections. Changing it back to named pipes (followed by a reboot) fixes it. [instructions](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-error-message-0x00000709-while/c16a136d-a935-43a2-bbe1-9364a8d9379c).

**Comment by jjkeijser** [comment]
Thanks for posting the solution - I have never tested print forwarding with this tutorial but glad to know it is now working again.
