### ISSUE TITLE
Offline Files do not work

### ISSUE THREAD

**Issue by regisdenice** [jjkeijser/cifs-over-ssh#4]
Offline files do not work

Details:
- I followed the [Windows 7 Tutorial](https://jjkeijser.github.io/cifs-over-ssh/Win7/) on a Windows 7 Pro SP1 x64 
- I am able to reach files (CRUD) from the SMB server (over SSH) - Thanks :smiley:  :+1:
- But I cannot make work the offline file

Reproducing error:
Given that my Window Explorer is open on the remote SMB folder
Given that I right-clicked a folder and selected "Always available offline"
When I click on Sync Center > View sync partnerships > Sync
Then I get errors for all files : "The process cannot access the file because this file is in use by another process"

Can you make it work on your side ?
Did I forget something ?

**Comment by jjkeijser** [comment]
This is the first time I've used the 'offline file' feature; on Windows 11 Ent it works fine , when connecting to a non-Samba share. Can you check whether it works for you when you're connected directly to the share (i.e. not using cifs-over-ssh) ?  

It might very well be that you need to enable opportunistic locking in Samba for offline files to work.

I cannot test this with Windows 7 easily, as that OS has been obsoleted several years ago.

**Comment by regisdenice** [comment]
You were indeed right @jjkeijser :smiley:  :+1: the **problem was on the server side**.

The problem did not come from cifs-over-ssh but from my Samba server. The Samba server was configured to do not allow remote client to shadow files. It's a pretty weird default feature, but so be it.

On my Samba server I changed the default SMB settings to:
- **Enable Opportunistic Locking** (the client can better cache file contents and avoid small read/write overhead)
- **Enable SMB durable handles** (allows users to restore lost SMB2 connection after temporary disconnection)
- **Synchronize data to drive immediately upon SMB client request** (immediately when requested by SMB clients)

Thank you :white_heart:
